name: Hola mundo

on: [push]

jobs:
    hola:  
      runs-on: windows-latest

        steps:
            - name: Hola mundo
              run: echo "Hola xavier"
            - name: touch file
              run: touch hola.txt
            - name: Set text
              run: echo "Hola Mundo" >>hola.txt

    other:
        runs-on: windows-latest
        needs: [hola]
        steps:
            - name: Checkout
              uses: actions/checkout@v4.2.2
            - name: LS
              run: dir
